# Generated by Django 6.0.5 on 2026-05-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_options_book_cover_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descriptions',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
