# Generated by Django 6.0.5 on 2026-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descriptions',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
