# Generated by Django 6.0.5 on 2026-06-11 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['id'], name='book_id_index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='book_title_index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='book_author_index'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book'], name='review_book_index'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author'], name='review_author_index'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='review_created_at_index'),
        ),
    ]
